name: JD Monitor

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Show Python Version
        run: python --version

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run JD Monitor
        run: python main.py
